services:
  - type: web
    name: hate-speech-api
    env: python
    region: oregon  # Choose your preferred region
    plan: free  # Use 'starter' or higher for production
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
